# Generated by Django 5.0.14 on 2026-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsevent_teammember_education_teammember_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
