# Generated by Django 6.0.3 on 2026-05-09 13:43

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_awarded', models.CharField(help_text="Text description of points (e.g., '50 points' or '1 pt / 1000 FCFA').", max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Optional SVG path for the icon.')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_points', models.IntegerField(help_text='Minimum total points required to reach this tier.')),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#A58B7C', help_text='Hex color for the tier (e.g., #A58B7C).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRanking',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Reward Ranking',
                'verbose_name_plural': 'Customer Reward Rankings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TierBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=255)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='rewards.loyaltytier')),
            ],
        ),
    ]
