# Generated by Django 4.2.30 on 2026-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_events/')),
                ('date', models.DateField(blank=True, help_text='For events, this is the event date.', null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News & Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Detailed biography for the dedicated member page.', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(help_text='Short introductory bio.'),
        ),
    ]
