# Generated by Django 6.0.3 on 2026-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
