# Generated by Django 6.0.3 on 2026-03-26 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_amount', models.IntegerField(default=1, help_text='Number of points earned per specific amount spent.')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=1000.0, help_text='Amount to be spent to earn the points.', max_digits=10)),
                ('bonus_points', models.IntegerField(default=50, help_text='Bonus points for frequent transactions.')),
                ('bonus_threshold', models.IntegerField(default=5, help_text='Number of transactions within 30 days to trigger bonus points.')),
                ('points_to_cash_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='Cash value per point (e.g., 1000 points = 500 FCFA -> ratio = 0.50).', max_digits=8)),
                ('expiry_days', models.IntegerField(default=365, help_text='Days until earned points expire.')),
            ],
            options={
                'verbose_name': 'Reward Setting',
                'verbose_name_plural': 'Reward Settings',
            },
        ),
        migrations.CreateModel(
            name='RewardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed/expired.')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], max_length=20)),
                ('order_reference', models.CharField(blank=True, help_text='Order ID or reference code.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
