import os
import django
from django.utils import timezone
import random

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'jofa_brand.settings')
django.setup()

from blog.models import Post
from reviews.models import Review
from products.models import Product

def create_cameroon_blogs():
    print("Updating Cameroonian Blog Posts with rich content and images...")
    
    # We downloaded a placeholder image to media/blog/placeholder_skincare.jpg
    image_path = 'blog/placeholder_skincare.jpg'
    
    blogs_data = [
        {
            "title": "Why Shea Butter is the Secret to Glowing Skin in Douala's Climate",
            "content": """
                <h2>The Challenge of Humidity</h2>
                <p>Douala's naturally humid and tropical climate presents a unique challenge for skincare. The combination of heat, moisture, and urban pollution means your skin is constantly working overtime to maintain its balance. Many heavy moisturizers sit on the surface, clogging pores and causing breakouts, while lighter lotions often evaporate too quickly, leaving the skin feeling tight and dehydrated.</p>
                
                <h2>The Shea Butter Solution</h2>
                <p>This is where raw, unrefined Shea Butter comes in as a savior. Traditionally sourced across West and Central Africa, Shea Butter is incredibly rich in vitamins A, E, and F. Unlike synthetic emollients, Shea Butter mimics your skin's natural sebum, allowing it to penetrate deeply without leaving a greasy residue.</p>
                
                <h3>Top Benefits for Douala Residents:</h3>
                <ul>
                    <li><strong>Non-Comedogenic:</strong> Despite its thick texture, it won't clog pores when applied correctly.</li>
                    <li><strong>Anti-Inflammatory:</strong> Soothes irritation caused by heat and sweat.</li>
                    <li><strong>UV Protection:</strong> Offers mild, natural protection against the sun's rays.</li>
                </ul>
                
                <h2>How to Use It</h2>
                <p>To get the best results in a humid climate, always apply Shea Butter to damp skin immediately after showering. This locks in the moisture and allows the butter to absorb seamlessly. Explore JOFA's Shea-infused collection designed specifically to keep your skin glowing, not greasy, all day long in the heart of Douala.</p>
            """,
            "excerpt": "Discover how shea butter balances moisture and protects your skin in Douala's humid climate without causing breakouts."
        },
        {
            "title": "Top 5 Natural Ingredients for Sun Protection in Yaoundé",
            "content": """
                <h2>The Reality of Sun Exposure</h2>
                <p>In Yaoundé, the capital city resting on seven hills, the altitude and proximity to the equator mean the sun's UV rays are particularly intense, especially during the dry season. While applying a broad-spectrum SPF is non-negotiable for all skin tones, supplementing your routine with natural, antioxidant-rich ingredients can significantly boost your skin's defense mechanisms.</p>
                
                <h2>Our Top 5 Natural Protectors</h2>
                <ol>
                    <li><strong>Aloe Vera:</strong> Known for its incredible soothing properties, Aloe Vera contains aloin, which blocks up to 30% of ultraviolet rays. It's the perfect after-sun treatment to cool down the skin.</li>
                    <li><strong>Coconut Oil:</strong> While not a replacement for sunscreen, pure coconut oil has a natural SPF of about 4-5. It provides a protective barrier and is packed with antioxidants.</li>
                    <li><strong>Green Tea Extract:</strong> Rich in polyphenols, specifically EGCG, green tea applied topically helps to neutralize free radicals generated by UV exposure, preventing premature aging.</li>
                    <li><strong>Carrot Seed Oil:</strong> An underrated powerhouse, carrot seed oil is rich in beta-carotene and vitamin A, offering natural sun protection and aiding in cell regeneration.</li>
                    <li><strong>Red Raspberry Seed Oil:</strong> This remarkable oil absorbs both UVB and UVC rays, offering an extra layer of botanical defense against the harsh Yaoundé sun.</li>
                </ol>
                
                <h2>Building Your Defense</h2>
                <p>At JOFA, we carefully formulate our daytime moisturizers and serums with these natural ingredients. By layering these antioxidant powerhouses under your daily sunscreen, you create an impenetrable shield against environmental damage, keeping your melanin-rich skin flawless and protected.</p>
            """,
            "excerpt": "Learn about the top natural ingredients that offer extra sun protection and boost your skin's defense in Yaoundé."
        },
        {
            "title": "The Ultimate Harmattan Skincare Routine for Cameroonians",
            "content": """
                <h2>Understanding the Harmattan</h2>
                <p>The Harmattan season, characterized by dry, dusty trade winds blowing from the Sahara, can wreak havoc on Cameroonian skin. Dropping humidity levels strip the skin of its natural moisture, leading to ashiness, cracking, and severe dehydration. Your regular skincare routine simply won't cut it during these harsh months.</p>
                
                <h2>Step-by-Step Survival Routine</h2>
                <h3>1. Gentle Cleansing</h3>
                <p>Ditch harsh soaps and foaming cleansers that strip natural oils. Switch to a cream or oil-based cleanser. JOFA's hydrating cleansers remove dirt and dust without compromising your skin barrier.</p>
                
                <h3>2. Deep Hydration</h3>
                <p>Hydration is key. Immediately after cleansing, while your skin is still damp, apply a hydrating toner or essence rich in hyaluronic acid and glycerin. These humectants draw moisture from the air into your skin.</p>
                
                <h3>3. Seal with Heavy Moisturizers</h3>
                <p>This is the time to bring out the heavy artillery. You need occlusive ingredients to lock in the hydration. Look for thick body butters, balms, and facial oils containing Shea Butter, Cocoa Butter, and Squalane. Our JOFA Winter Collection is specifically formulated for this deep sealing action.</p>
                
                <h3>4. Exfoliate Wisely</h3>
                <p>While your skin may look flaky, over-exfoliating will only worsen the dryness. Limit physical scrubs and opt for gentle chemical exfoliants like lactic acid once a week to remove dead cells gently.</p>
                
                <h2>Protecting Your Lips and Hands</h2>
                <p>Don't forget the areas most prone to cracking. Carry a thick lip balm and a rich hand cream with you at all times. Consistency with this routine will ensure your skin stays soft and supple until the rains return.</p>
            """,
            "excerpt": "Combat dry, cracking skin during the harsh Harmattan season with this ultimate step-by-step hydration routine."
        },
        {
            "title": "How to Combat Hyperpigmentation: Tips for Melanin-Rich Skin",
            "content": """
                <h2>What is Hyperpigmentation?</h2>
                <p>Hyperpigmentation—dark spots, patches, and uneven skin tone—is one of the most common concerns for melanin-rich skin in Cameroon. Because our skin contains more melanin, any trauma (like a pimple, a scratch, or excess sun exposure) triggers the melanocytes to produce even more pigment, leaving behind a dark mark known as Post-Inflammatory Hyperpigmentation (PIH).</p>
                
                <h2>Effective Ingredients to Look For</h2>
                <p>Fading dark spots requires patience and the right active ingredients. Here are the most effective, science-backed ingredients that are safe for darker skin tones:</p>
                <ul>
                    <li><strong>Vitamin C:</strong> A powerful antioxidant that inhibits melanin production and brightens the overall complexion. It's a staple in JOFA's brightening serums.</li>
                    <li><strong>Niacinamide (Vitamin B3):</strong> Works by preventing the transfer of pigment within the skin. It also strengthens the skin barrier and reduces inflammation.</li>
                    <li><strong>Licorice Root Extract:</strong> A natural alternative to hydroquinone, it contains glabridin, which effectively disperses melanin and fades existing dark spots.</li>
                    <li><strong>Alpha Arbutin:</strong> A gentle botanical extract that slows down the enzymes that stimulate melanin production.</li>
                </ul>
                
                <h2>The Golden Rule: Sunscreen</h2>
                <p>All the brightening serums in the world will be useless if you do not protect your skin from the sun. UV rays darken existing hyperpigmentation. Applying a broad-spectrum SPF daily is the most critical step in treating and preventing dark spots.</p>
                
                <h2>The JOFA Approach</h2>
                <p>Our products are specifically formulated to tackle hyperpigmentation without using harsh bleaching agents that damage the skin barrier. With consistent use of our targeted serums and daily sun protection, you will see a visibly more even and radiant skin tone.</p>
            """,
            "excerpt": "Discover effective tips and science-backed ingredients to safely fade dark spots and uneven tone on melanin-rich skin."
        },
        {
            "title": "The Benefits of African Black Soap for Acne-Prone Skin",
            "content": """
                <h2>The Origins of Black Soap</h2>
                <p>Authentic African Black Soap is an ancestral beauty secret that has been used for centuries across West and Central Africa. Traditionally handcrafted from locally harvested plantain skins, cocoa pods, palm tree leaves, and shea tree bark, this soap is renowned for its incredible healing properties, especially for those suffering from acne and blemishes.</p>
                
                <h2>Why It Works for Acne</h2>
                <p>The secret lies in the ash of the roasted pods and barks, which gives the soap its dark color. This ash acts as a gentle, natural exfoliant, sloughing off dead skin cells that can clog pores. Furthermore, Black Soap has profound antibacterial and anti-fungal properties, making it highly effective at killing acne-causing bacteria.</p>
                
                <h3>Key Benefits:</h3>
                <ul>
                    <li><strong>Deep Cleansing:</strong> It penetrates deep into the pores to remove excess sebum and impurities.</li>
                    <li><strong>Reduces Inflammation:</strong> The inclusion of Shea Butter and Palm Kernel Oil helps soothe inflamed, red acne lesions.</li>
                    <li><strong>Fades Blemishes:</strong> Regular use helps in fading acne scars and evening out the skin tone.</li>
                </ul>
                
                <h2>How to Use It Correctly</h2>
                <p>Because authentic Black Soap is highly alkaline and potent, it can be drying if overused. It's crucial to follow up with a deeply hydrating toner and a rich moisturizer. At JOFA, we have refined traditional Black Soap into gentle, pH-balanced cleansers that deliver all the acne-fighting benefits without stripping your skin's natural moisture barrier.</p>
            """,
            "excerpt": "Learn why traditional African Black Soap is a powerhouse for treating acne naturally and effectively."
        },
        {
            "title": "Hydration vs. Moisture: What Your Skin Needs in Bamenda",
            "content": """
                <h2>Understanding the Difference</h2>
                <p>In regions with cooler, fluctuating climates like Bamenda in the Northwest, many people struggle with dry, tight skin despite applying heavy creams. The culprit is often a misunderstanding between two critical skincare concepts: Hydration and Moisture. While they sound similar, they serve entirely different purposes.</p>
                
                <h2>What is Hydration?</h2>
                <p>Hydration refers to the water content within the cells of your skin. When skin is dehydrated, it looks dull, feels tight, and fine lines become more visible. Dehydrated skin lacks <em>water</em>. To fix this, you need humectants—ingredients that bind water to the skin. </p>
                <ul>
                    <li><strong>Key Humectants:</strong> Hyaluronic Acid, Glycerin, Aloe Vera, and Honey.</li>
                </ul>
                
                <h2>What is Moisture?</h2>
                <p>Moisturizing is about trapping and sealing that hydration into the skin so it doesn't evaporate into the cool Bamenda air (a process called Transepidermal Water Loss or TEWL). Dry skin lacks <em>oil</em>. To fix this, you need emollients and occlusives.</p>
                <ul>
                    <li><strong>Key Occlusives:</strong> Shea Butter, Cocoa Butter, Squalane, and natural botanical oils.</li>
                </ul>
                
                <h2>The Perfect Routine</h2>
                <p>To achieve healthy, glowing skin in cooler climates, you must do both. Always apply your hydrating water-based serums (like JOFA's Hyaluronic Essence) first, on slightly damp skin. Then, immediately follow up with a thicker, oil-based moisturizer or cream to lock that water in. This two-step process ensures your skin remains plump, protected, and perfectly balanced.</p>
            """,
            "excerpt": "Understand the crucial difference between hydration and moisture to maintain healthy, plump skin in cooler climates like Bamenda."
        },
        {
            "title": "Embracing Your Natural Glow: The JOFA Philosophy",
            "content": """
                <h2>Redefining Beauty Standards</h2>
                <p>For decades, the beauty industry has often pushed standards that don't align with the reality of melanin-rich skin. At JOFA, we are on a mission to change the narrative. We believe that true skincare is not about altering your complexion or conforming to unrealistic ideals; it is about nurturing, protecting, and enhancing the beautiful skin you were born with.</p>
                
                <h2>Nature Meets Science</h2>
                <p>Our philosophy is deeply rooted in the synergy between ancestral African botanicals and modern dermatological science. We source the finest, ethically harvested ingredients from the rich soils of Cameroon and the continent—like Baobab oil, Marula, and Shea—and formulate them using cutting-edge techniques to maximize their efficacy and safety.</p>
                
                <h2>Formulated for Us</h2>
                <p>Melanin-rich skin has unique structural differences; it is more prone to hyperpigmentation, tends to be more sensitive to harsh chemicals, and requires specific types of hydration. Every JOFA product is meticulously crafted with these unique needs in mind. We formulate without harsh bleaching agents, toxic parabens, or stripping sulfates.</p>
                
                <h2>Join the Movement</h2>
                <p>When you choose JOFA, you are choosing a brand that celebrates your natural glow. We invite you to embrace a skincare journey that prioritizes health, self-love, and the radiant confidence that comes from knowing your skin is deeply cared for.</p>
            """,
            "excerpt": "Discover the JOFA philosophy of prioritizing skin health, self-love, and enhancing your natural beauty with premium ingredients."
        },
        {
            "title": "Understanding Your Skin Type: A Guide for Cameroonian Women",
            "content": """
                <h2>The Foundation of Skincare</h2>
                <p>The biggest mistake you can make in your skincare journey is using the wrong products for your skin type. What works miracles for your best friend might cause severe breakouts for you. Understanding your specific skin type is the absolute foundation of building an effective routine.</p>
                
                <h2>The 4 Main Skin Types</h2>
                <h3>1. Oily Skin</h3>
                <p>Characterized by excess sebum production, leading to a shiny appearance, especially in the T-zone, and prone to acne and enlarged pores. <strong>JOFA Tip:</strong> Use lightweight, gel-based moisturizers and salicylic acid cleansers.</p>
                
                <h3>2. Dry Skin</h3>
                <p>Produces less sebum than normal skin, resulting in a tight, flaky, or rough texture. It often looks dull. <strong>JOFA Tip:</strong> Focus on heavy creams, rich facial oils, and gentle, non-foaming cleansers.</p>
                
                <h3>3. Combination Skin</h3>
                <p>The most common skin type. Features an oily T-zone (forehead, nose, chin) but normal to dry cheeks. <strong>JOFA Tip:</strong> You may need to "multi-treat" by using lighter products on your T-zone and richer creams on your cheeks.</p>
                
                <h3>4. Sensitive Skin</h3>
                <p>Easily irritated by environmental factors, fragrances, and harsh chemicals. Prone to redness, itching, and rashes. <strong>JOFA Tip:</strong> Stick to hypoallergenic, fragrance-free JOFA products with soothing ingredients like Aloe and Chamomile.</p>
                
                <h2>The Bare-Faced Test</h2>
                <p>To determine your skin type, wash your face with a gentle cleanser and pat dry. Do not apply any products. Wait 30 minutes. If your face feels tight, you have dry skin. If there is noticeable shine on your nose and forehead, you have combination skin. If there is shine everywhere, you have oily skin. Once you know your type, you can confidently shop the JOFA collections tailored just for you.</p>
            """,
            "excerpt": "A comprehensive guide to identifying your skin type and choosing the right products for a balanced, healthy complexion."
        },
        {
            "title": "The Importance of Exfoliation for a Radiant Complexion",
            "content": """
                <h2>Why We Need to Exfoliate</h2>
                <p>Our skin naturally sheds dead cells every 28 days. However, as we age, or due to environmental factors, this process slows down. Dead skin cells begin to pile up on the surface, leading to a dull, ashy complexion, clogged pores, and rough texture. Exfoliation is the process of removing this buildup to reveal the fresh, radiant skin underneath.</p>
                
                <h2>Physical vs. Chemical Exfoliation</h2>
                <p>For melanin-rich skin, the method of exfoliation is critical. </p>
                <ul>
                    <li><strong>Physical Exfoliants:</strong> Think apricot scrubs or facial brushes. While popular, these can cause micro-tears in the skin, leading to inflammation and hyperpigmentation (dark spots). We generally advise caution with physical scrubs on the face.</li>
                    <li><strong>Chemical Exfoliants:</strong> These utilize gentle acids to dissolve the bonds between dead skin cells. This is the preferred method for Cameroonian skin.</li>
                </ul>
                
                <h2>Alpha and Beta Hydroxy Acids (AHAs & BHAs)</h2>
                <p><strong>AHAs (like Lactic or Glycolic Acid):</strong> Water-soluble acids that work on the surface of the skin. They are fantastic for brightening, smoothing texture, and fading dark spots.</p>
                <p><strong>BHAs (like Salicylic Acid):</strong> Oil-soluble acids that can penetrate deep into the pores. They are the holy grail for treating acne, blackheads, and oily skin.</p>
                
                <h2>How to Incorporate It safely</h2>
                <p>Start slowly. Exfoliate only 1-2 times a week at night. Always follow up with a rich JOFA moisturizer to soothe the new skin cells, and absolutely never skip your sunscreen the next morning, as exfoliated skin is more sensitive to UV rays.</p>
            """,
            "excerpt": "Learn why gentle chemical exfoliation is the key to a bright, radiant complexion and how to do it safely."
        },
        {
            "title": "Skincare Myths Debunked: What You Need to Know",
            "content": """
                <h2>Separating Fact from Fiction</h2>
                <p>The world of skincare is full of passed-down advice, internet hacks, and marketing gimmicks. Many of these myths are not only ineffective but can actively damage your skin barrier. Let's debunk some of the most persistent skincare myths we hear in Cameroon.</p>
                
                <h3>Myth 1: "Black people don't need sunscreen."</h3>
                <p><strong>Fact:</strong> While melanin provides a natural SPF of around 13, it is not enough to protect against intense UV rays. Unprotected sun exposure leads to hyperpigmentation, premature aging, and increases the risk of skin cancer. Everyone needs sunscreen, every single day.</p>
                
                <h3>Myth 2: "Oily skin doesn't need moisturizer."</h3>
                <p><strong>Fact:</strong> Skipping moisturizer can actually make your skin oilier! When your skin is dehydrated, it overcompensates by producing more sebum. Oily skin still needs hydration; just opt for lightweight, oil-free moisturizers or gel creams from the JOFA line.</p>
                
                <h3>Myth 3: "If it burns, it means it's working."</h3>
                <p><strong>Fact:</strong> Skincare should never burn. A slight tingle from active ingredients (like AHAs) is normal, but burning or stinging is a sign that your skin barrier is being damaged and inflammation is occurring. Wash the product off immediately.</p>
                
                <h3>Myth 4: "Natural ingredients are always better."</h3>
                <p><strong>Fact:</strong> Poison ivy is natural, but you wouldn't put it on your face. Many synthetic ingredients (like Hyaluronic acid or Niacinamide) are incredibly safe and effective, while some natural ingredients (like essential oils or lemon juice) can be highly irritating. JOFA uses the best of both safe science and nature.</p>
            """,
            "excerpt": "We debunk common skincare myths that could be harming your skin, from sunscreen facts to moisturization."
        },
        {
            "title": "The Power of Antioxidants in Your Skincare Routine",
            "content": """
                <h2>What Are Free Radicals?</h2>
                <p>Living in bustling urban centers like Douala and Yaoundé exposes our skin to a high level of environmental stressors: car exhaust, industrial pollution, and intense UV rays. These stressors generate "free radicals"—unstable molecules that damage healthy skin cells, break down collagen, and accelerate premature aging and hyperpigmentation.</p>
                
                <h2>Antioxidants to the Rescue</h2>
                <p>Antioxidants are the superheroes of skincare. They neutralize free radicals by donating an electron, effectively stopping the damage in its tracks. Incorporating antioxidants into your morning routine is essential for protecting your skin throughout the day.</p>
                
                <h2>Top Antioxidants for Your Skin</h2>
                <ul>
                    <li><strong>Vitamin C (Ascorbic Acid):</strong> The gold standard. It not only protects against pollution but also brightens the skin and boosts collagen production.</li>
                    <li><strong>Vitamin E:</strong> A highly moisturizing antioxidant that works beautifully in synergy with Vitamin C to strengthen the skin barrier.</li>
                    <li><strong>Green Tea Extract:</strong> Exceptional for soothing inflammation and reducing redness while fighting free radicals.</li>
                    <li><strong>Resveratrol:</strong> Found in grapes and berries, it is a potent anti-aging ingredient that protects the skin's surface.</li>
                </ul>
                
                <h2>The JOFA Shield</h2>
                <p>We infuse our daytime serums and light moisturizers with a potent blend of these antioxidants. Applying a JOFA Vitamin C serum under your daily sunscreen provides the ultimate defense against the Cameroonian elements, keeping your skin bright, firm, and healthy.</p>
            """,
            "excerpt": "Discover how antioxidants protect your skin from environmental damage, pollution, and premature aging."
        },
        {
            "title": "Nighttime Skincare: Why It Matters More Than You Think",
            "content": """
                <h2>The Science of Beauty Sleep</h2>
                <p>You might wonder why you need a separate routine for nighttime. The answer lies in your body's circadian rhythm. During the day, your skin is in "defense mode," fighting off UV rays and pollution. But at night, while you sleep, your skin switches into "repair and regeneration mode." Blood flow to the skin increases, and cellular turnover is at its peak.</p>
                
                <h2>Maximizing the Repair Process</h2>
                <p>Because your skin is actively repairing itself, it is highly receptive to active ingredients at night. This is the time to apply targeted treatments that might make your skin sensitive to the sun during the day.</p>
                
                <h3>The Ideal Night Routine:</h3>
                <ol>
                    <li><strong>Double Cleansing:</strong> Start with an oil-based cleanser to break down makeup and sunscreen, followed by a water-based cleanser to remove sweat and dirt.</li>
                    <li><strong>Treatment Serums:</strong> Apply your active ingredients. This is the perfect time for Retinol (for anti-aging) or strong exfoliating acids (for texture and hyperpigmentation).</li>
                    <li><strong>Deep Moisturization:</strong> Your skin loses more water at night (TEWL). Seal in your treatments with a thick, nourishing night cream or sleeping mask. JOFA's restorative night creams are packed with ceramides and peptides to support the skin's rebuilding process.</li>
                </ol>
                
                <h2>Wake Up Glowing</h2>
                <p>A consistent, thoughtful nighttime routine ensures that you wake up with plump, hydrated, and rejuvenated skin, ready to face whatever the day in Cameroon throws at you.</p>
            """,
            "excerpt": "Learn how to maximize your skin's natural overnight repair process with a targeted nighttime routine."
        },
        {
            "title": "Dealing with Sensitive Skin: Tips for Gentle Care",
            "content": """
                <h2>Identifying Sensitive Skin</h2>
                <p>Sensitive skin is more of a condition than a fixed skin type. It occurs when the skin's protective lipid barrier is weakened, allowing irritants to penetrate easily. Symptoms include frequent redness, stinging, burning sensations, extreme dryness, and easily triggered rashes. If this sounds familiar, your skincare routine needs a major overhaul.</p>
                
                <h2>What to Avoid</h2>
                <p>The first step in managing sensitive skin is eliminating common triggers:</p>
                <ul>
                    <li><strong>Artificial Fragrances:</strong> The number one cause of contact dermatitis in skincare. Opt for fragrance-free products.</li>
                    <li><strong>Harsh Exfoliants:</strong> Avoid physical scrubs (like walnut shells) and high-percentage chemical acids.</li>
                    <li><strong>Drying Alcohols:</strong> Ingredients like SD alcohol or denatured alcohol strip the skin of vital lipids.</li>
                </ul>
                
                <h2>How to Soothe and Rebuild</h2>
                <p>Your goal is to calm inflammation and rebuild the compromised skin barrier. Look for products containing ceramides, fatty acids, and cholesterol, which act like the mortar between your skin cells.</p>
                <p>Soothing botanicals are also your best friend. JOFA's Sensitive Skin line heavily features Centella Asiatica (Gotu Kola), Aloe Vera, and Colloidal Oatmeal to instantly calm redness and irritation. Keep your routine simple: a gentle milky cleanser, a hydrating serum, and a barrier-repairing moisturizer. Less is always more when dealing with sensitivity.</p>
            """,
            "excerpt": "Gentle skincare tips, ingredient recommendations, and triggers to avoid for sensitive and easily irritated skin types."
        },
        {
            "title": "The Link Between Diet and Skin Health",
            "content": """
                <h2>Beauty From the Inside Out</h2>
                <p>While premium topical skincare from JOFA works wonders, the reality is that your skin reflects your internal health. The food you consume provides the building blocks for new skin cells, collagen, and hormones. A poor diet can undermine the best skincare routine.</p>
                
                <h2>Foods That Trigger Skin Issues</h2>
                <p>High-glycemic foods (like refined sugar, white bread, and pastries) cause insulin spikes, which trigger inflammation and increase sebum production—a perfect recipe for acne breakouts. For some individuals, dairy can also exacerbate hormonal acne. Moderation is key.</p>
                
                <h2>Superfoods for a Glowing Complexion</h2>
                <p>Cameroon is blessed with an abundance of fresh, nutrient-dense foods that promote radiant skin. Make sure to incorporate these into your diet:</p>
                <ul>
                    <li><strong>Avocados:</strong> Packed with healthy fats and Vitamin E to keep skin supple and moisturized from within.</li>
                    <li><strong>Papaya (Pawpaw):</strong> Rich in Vitamin C for collagen production and the enzyme papain, which helps reduce inflammation.</li>
                    <li><strong>Dark Leafy Greens:</strong> Ndolé, Spinach, and Waterleaf are full of antioxidants, vitamins, and minerals that protect against cellular damage.</li>
                    <li><strong>Nuts and Seeds:</strong> Groundnuts and pumpkin seeds offer essential zinc and omega fatty acids for a strong skin barrier.</li>
                </ul>
                
                <h2>Hydration is Crucial</h2>
                <p>Drinking adequate water is the most fundamental step for clear skin. It flushes out toxins and keeps cells hydrated. Pair a healthy, colorful diet with your JOFA skincare regimen for truly unstoppable, glowing skin.</p>
            """,
            "excerpt": "How your diet affects your skin and which local Cameroonian foods promote a healthy, radiant glow from the inside out."
        },
        {
            "title": "Self-Care Sunday: Creating a Spa Experience at Home",
            "content": """
                <h2>The Importance of Unwinding</h2>
                <p>In the hustle and bustle of daily life, stress takes a significant toll on your skin, leading to premature aging, dullness, and stress-induced breakouts. Taking time once a week to intentionally slow down, decompress, and pamper your skin is not just a luxury; it's a necessity for holistic wellness.</p>
                
                <h2>Setting the Scene</h2>
                <p>Transform your bathroom into a sanctuary. Dim the lights, light a lightly scented candle (like lavender or eucalyptus), and put on some calming instrumental music. The goal is to engage all your senses in relaxation.</p>
                
                <h2>The At-Home Spa Protocol</h2>
                <ol>
                    <li><strong>The Steam:</strong> After double-cleansing, safely hover your face over a bowl of hot water for 5 minutes. The steam softens the skin and opens up the pores, preparing it for treatments.</li>
                    <li><strong>The Mask:</strong> Apply a JOFA clarifying clay mask if you're feeling congested, or a thick, hydrating cream mask if you're dry. Leave it on for 15 minutes while you close your eyes and relax.</li>
                    <li><strong>The Massage:</strong> Rinse off the mask and apply a generous amount of our luxurious JOFA Glow Oil. Use your fingertips or a Gua Sha tool to gently massage your face, neck, and shoulders. This stimulates lymphatic drainage, reduces puffiness, and gives an instant lift.</li>
                    <li><strong>The Seal:</strong> Finish by pressing a rich night cream into the skin.</li>
                </ol>
                <p>Take this time to disconnect from your phone and reconnect with yourself. You'll wake up on Monday with a clear mind and incredibly radiant skin.</p>
            """,
            "excerpt": "A step-by-step guide to setting up a relaxing and rejuvenating at-home spa experience for ultimate skin health."
        }
    ]

    for data in blogs_data:
        # Check if we should update or create
        post, created = Post.objects.get_or_create(
            title=data['title'],
            defaults={
                'content': data['content'],
                'excerpt': data['excerpt'],
                'author': 'JOFA Team',
                'published': True,
                'image': image_path
            }
        )
        # If it already existed, update the content and image
        if not created:
            post.content = data['content']
            post.excerpt = data['excerpt']
            post.image = image_path
            post.save()
            
    print(f"Updated/Created {len(blogs_data)} blog posts with rich content and images.")

def create_cameroon_reviews():
    print("Skipping reviews population for this update...")
    # Kept empty to only focus on blog content

if __name__ == '__main__':
    create_cameroon_blogs()
    # create_cameroon_reviews()
    print("SEO Blog Content Expansion Complete.")
