# Generated by Django 5.0.14 on 2026-08-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone_number'),
        ('vendors', '0001_marketplace_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vendors.vendor'),
        ),
    ]
