# Generated by Django 5.0.14 on 2026-08-11 16:03

import consultation.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=consultation.models.consultation_upload_to)),
                ('angle', models.CharField(choices=[('face', 'Full face'), ('cheek', 'Cheek'), ('forehead', 'Forehead'), ('other', 'Other')], default='face', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkinConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('age_range', models.CharField(blank=True, max_length=20)),
                ('declared_skin_type', models.CharField(blank=True, choices=[('', 'Not sure'), ('dry', 'Dry'), ('oily', 'Oily'), ('sensitive', 'Sensitive'), ('combination', 'Combination'), ('all', 'Normal / Balanced')], max_length=20)),
                ('primary_goals', models.TextField(blank=True, help_text='User-described goals / concerns')),
                ('sensitivity_level', models.PositiveSmallIntegerField(default=2, help_text='1=low … 5=high')),
                ('consent_analysis', models.BooleanField(default=False)),
                ('consent_image_retention', models.BooleanField(default=False, help_text='If false, photos are deleted after analysis.')),
                ('detected_skin_type', models.CharField(blank=True, max_length=20)),
                ('analysis_summary', models.TextField(blank=True)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analyzer_backend', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
