# Generated by Django 5.0.14 on 2026-08-11 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('products', '0005_alter_category_slug_alter_product_slug'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skinconsultation',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='recommendations.skinconcern'),
        ),
        migrations.AddField(
            model_name='skinconsultation',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='consultation_recs', to='products.product'),
        ),
        migrations.AddField(
            model_name='skinconsultation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationphoto',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='consultation.skinconsultation'),
        ),
    ]
