name: Déploiement Automatique Namecheap

on:
  push:
    branches:
      - main # Remplacez par le nom de votre branche si nécessaire

jobs:
  web-deploy:
    name: Déployer le code
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4
      
    - name: Synchroniser les fichiers via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21 # Basculé sur le port FTP standard pour éviter le timeout
        server-dir: /home/jofafzby/ # Modifiez si votre site est dans un sous-dossier
