name: Déploiement Automatique Namecheap

on:
  push:
    branches:
      - main # Déclenche le déploiement quand on pousse sur la branche main

jobs:
  web-deploy:
    name: Déployer le code
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4
      
    - name: Synchroniser les fichiers via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 2102 # Port standard SSH/SFTP chez Namecheap
        server-dir: /home/jofafzby/ # Modifiez si votre site est dans un sous-dossier
