# Generated by Django 5.0.14 on 2026-08-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('skin_type', models.CharField(blank=True, help_text='Optional primary Product.skin_type target', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords used by the heuristic analyzer.')),
                ('related_skin_types', models.CharField(blank=True, help_text='Comma-separated Product.skin_type values (dry,oily,...)', max_length=120)),
                ('severity_weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('treatment', 'Treatment'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('mask', 'Mask'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recommendations.routinebundle')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('routine', 'product')},
            },
        ),
        migrations.AddField(
            model_name='routinebundle',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='routines', through='recommendations.RoutineStep', to='products.product'),
        ),
        migrations.AddField(
            model_name='routinebundle',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='routines', to='recommendations.skinconcern'),
        ),
        migrations.CreateModel(
            name='ConcernProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower = higher priority')),
                ('role', models.CharField(blank=True, help_text='e.g. cleanser, serum, moisturizer, treatment, sunscreen', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_maps', to='products.product')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_maps', to='recommendations.skinconcern')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'unique_together': {('concern', 'product')},
            },
        ),
    ]
