# Generated by Django 5.0.14 on 2026-08-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_slug_alter_product_slug'),
        ('vendors', '0001_marketplace_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Marketplace seller who owns this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='vendors.vendor'),
        ),
    ]
